'''
SAM+YOLOv9

(sam1) C:\Users\21344>conda list
# packages in environment at D:\Anaconda3\envs\sam1:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
aiohappyeyeballs          2.3.5                    pypi_0    pypi
aiohttp                   3.10.3                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albucore                  0.0.17                   pypi_0    pypi
albumentations            1.4.18                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
blinker                   1.8.2                    pypi_0    pypi
brotli-python             1.0.9           py310hd77b12b_8    defaults
bzip2                     1.0.8                h2bbff1b_6    defaults
ca-certificates           2024.7.2             haa95532_0    defaults
certifi                   2024.7.4        py310haa95532_0    defaults
charset-normalizer        3.3.2              pyhd3eb1b0_0    defaults
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6           py310haa95532_0    defaults
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dash                      2.18.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
distinctipy               1.3.4                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
filelock                  3.13.1          py310haa95532_0    defaults
flask                     3.0.3                    pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.4.10                        0    defaults
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gmpy2                     2.1.2           py310h7f96b67_0    defaults
grpcio                    1.66.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.7             py310haa95532_0    defaults
imageio                   2.34.2                   pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
intel-openmp              2021.4.0                 pypi_0    pypi
ipython                   8.28.0                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4           py310haa95532_0    defaults
jpeg                      8d                            0    defaults
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libffi                    3.4.4                hd77b12b_1    defaults
libiconv                  1.16                 h2bbff1b_3    defaults
libjpeg-turbo             2.0.0                h196d8e1_0    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.2                         1    defaults
libuv                     1.48.0               h827c3e9_0    defaults
libwebp                   1.2.2                h2bbff1b_0    defaults
libxml2                   2.13.1               h24da03e_2    defaults
libxslt                   1.1.41               h0739af5_0    defaults
lightning                 2.4.0                    pypi_0    pypi
lightning-utilities       0.11.6                   pypi_0    pypi
lxml                      5.2.1           py310h395c83e_1    defaults
markdown                  3.7                      pypi_0    pypi
markupsafe                2.1.3           py310h2bbff1b_0    defaults
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
mkl-service               2.4.0           py310h2bbff1b_1    defaults
mkl_fft                   1.3.8           py310h2bbff1b_0    defaults
mkl_random                1.2.4           py310h59b6b97_0    defaults
mpc                       1.1.0                h7edee0f_1    defaults
mpfr                      4.0.2                h62dcd97_1    defaults
mpir                      3.0.0                hec2e145_1    defaults
mpmath                    1.3.0           py310haa95532_0    defaults
multidict                 6.0.5                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3             py310haa95532_0    defaults
numpy                     1.26.4          py310h055cbcc_0    defaults
numpy-base                1.26.4          py310h65a83cf_0    defaults
onnx                      1.16.1                   pypi_0    pypi
onnxruntime               1.18.1                   pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.10.0.84                pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.14               h827c3e9_0    defaults
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0    defaults
platformdirs              4.3.6                    pypi_0    pypi
plotly                    5.24.1                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  5.27.2                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyapriltags               3.3.0.3                  pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyqt5                     5.15.11                  pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.15.0                  pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
pyrealsense2              2.55.1.6486              pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.14              he1021f5_1    defaults
python-box                7.2.0                    pypi_0    pypi
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         2.4.0                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2024.2                   pypi_0    pypi
pywin32                   308                      pypi_0    pypi
pyyaml                    6.0.1           py310h2bbff1b_0    defaults
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3          py310haa95532_0    defaults
retrying                  1.3.4                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
segment-anything          1.0                       dev_0    <develop>
setuptools                69.5.1          py310haa95532_0    defaults
shapely                   2.0.6                    pypi_0    pypi
simplification            0.7.12                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tbb                       2021.13.0                pypi_0    pypi
tenacity                  9.0.0                    pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
tifffile                  2024.7.24                pypi_0    pypi
tk                        8.6.14               h0416ee5_0    defaults
torch                     2.3.0+cu118              pypi_0    pypi
torchaudio                2.3.0+cu118              pypi_0    pypi
torchmetrics              1.4.1                    pypi_0    pypi
torchvision               0.18.0+cu118             pypi_0    pypi
tqdm                      4.66.4          py310h9909e9c_0    defaults
traitlets                 5.14.3                   pypi_0    pypi
typing_extensions         4.11.0          py310haa95532_0    defaults
tzdata                    2024.2                   pypi_0    pypi
ultralytics               8.3.13                   pypi_0    pypi
ultralytics-thop          2.0.9                    pypi_0    pypi
urllib3                   2.2.2           py310haa95532_0    defaults
vc                        14.2                 h2eaa2aa_4    defaults
vs2015_runtime            14.29.30133          h43f2093_4    defaults
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.43.0          py310haa95532_0    defaults
widgetsnbextension        4.0.13                   pypi_0    pypi
win_inet_pton             1.1.0           py310haa95532_0    defaults
xz                        5.4.6                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1    defaults

(sam1) C:\Users\21344>



'''